/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tako
 */
public class tumIslemler extends javax.swing.JFrame {
    
    //Kullanıcının istediği ekranı listelemesi için gerekli işlemlerin yapılıp jFrame lere yönlendiren ekran

    /**
     * Creates new form tumİslemler
     */
    public tumIslemler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calisanlar = new javax.swing.JButton();
        tedarikciTablosu = new javax.swing.JButton();
        urunlerTablosu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calisanlar.setText("Çalışanlar Tablosu");
        calisanlar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calisanlarMouseClicked(evt);
            }
        });
        calisanlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisanlarActionPerformed(evt);
            }
        });

        tedarikciTablosu.setText("Tedarikci Tablosu");
        tedarikciTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tedarikciTablosuMouseClicked(evt);
            }
        });

        urunlerTablosu.setText("Ürünler Tablosu");
        urunlerTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urunlerTablosuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calisanlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(urunlerTablosu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tedarikciTablosu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(calisanlar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urunlerTablosu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tedarikciTablosu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calisanlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisanlarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calisanlarActionPerformed

    private void calisanlarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calisanlarMouseClicked
        // TODO add your handling code here:
        calisanlarEkrani calisanlarEkrani1 = new calisanlarEkrani();
        calisanlarEkrani1.setVisible(true);
    }//GEN-LAST:event_calisanlarMouseClicked

    private void urunlerTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urunlerTablosuMouseClicked
        // TODO add your handling code here:
        urunlerEkrani urunlerEkrani1 = new urunlerEkrani();
            urunlerEkrani1.setVisible(true);
    }//GEN-LAST:event_urunlerTablosuMouseClicked

    private void tedarikciTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tedarikciTablosuMouseClicked
        // TODO add your handling code here:
        tedarikciEkrani tedarikciEkrani1 = new tedarikciEkrani();
            tedarikciEkrani1.setVisible(true);
    }//GEN-LAST:event_tedarikciTablosuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tumIslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tumIslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tumIslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tumIslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tumIslemler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calisanlar;
    private javax.swing.JButton tedarikciTablosu;
    private javax.swing.JButton urunlerTablosu;
    // End of variables declaration//GEN-END:variables
}
